site_name: Airbreach
site_description: Obsidian How-To Guides served with MkDocs + Material
site_author: DirtyOptics

docs_dir: docs
site_dir: site

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.annotate
    - search.suggest
    - search.highlight
    - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

plugins:
  - search
  - minify
#  - git-revision-date-localized  # Uncomment if you want last updated dates

markdown_extensions:
  - admonition       # ✅ Callouts/notes
  - footnotes
  - codehilite
  - attr_list
  - def_list
  - toc:
      permalink: true
  - tables

nav:
  - Home: index.md
  - Networking:
      - Setup Nanostation: networking/setup-nanostation.md
  - Raspberry Pi:
      - Enable VNC: raspberry-pi/enable-vnc.md

