site_name: Airbreach
site_description: Obsidian How-To Guides served with MkDocs + Material
site_author: DirtyOptics

docs_dir: docs
site_dir: site

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - search.suggest
    - search.highlight
    - search.share
    - toc.follow
    - toc.integrate
    - content.action.edit
    - content.action.view
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye

# Custom CSS
extra_css:
  - stylesheets/extra.css

# Navigation configuration
nav:
  - Home: index.md
  - Networking:
      - Setup Nanostation: networking/setup-nanostation.md
  - Raspberry Pi:
      - Enable VNC: raspberry-pi/enable-vnc.md
  - Proxmox:
    - PCI Passthrough: proxmox/PROXMOX-PCI Passthrough.md

# Table of contents configuration
markdown_extensions:
  - admonition       # ✅ Callouts/notes
  - footnotes
  - codehilite:
      guess_lang: true
      use_pygments: true
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true
      title: On this page
  - tables
  - pymdownx.tasklist:
      custom_checkbox: true


plugins:
  - search:
      lang: en
  - minify:
      minify_html: true
#  - git-revision-date-localized:
#      enable_creation_date: true
#      enable_modification_date: true
#      type: timeago


